### PR TITLE
Add figures for publication

### PR DESCRIPTION
**Pull request by marwahaha**
new file here: https://github.com/QAOAKit/QAOAKit/blob/2c51637297f4450f084aad3d59a5df1754670405/examples/performance.ipynb

I made the last plot vertical, and added "savefig" commands (I didn't check in the images though)

### CODE REVIEW

**Comment by marwahaha** [comment]
Sorry for the delay.

This comes from this paper http://statweb.stanford.edu/~adembo/preprints/AOP1084.pdf showing that for sparse, large, random graphs, the maximum cut is almost always 1/2 + P/sqrt(D), where P is approximately 0.7632....

So we know for a sparse random graph, we should see a 1/sqrt(D) correlation. However, we may not see it at these small sizes.

Does that make sense? I can add to the notebook once it is clear to you.

**Comment by rsln-s** [comment]
So this makes the assumption that QAOA approximation ratio is constant, right? I attempted to articulate on overleaf:

> In sparse random graphs, the value of the optimal cut scales as $1/2 + O(1/\sqrt{d})$ with the average degree $d$ of the graph~\cite{dembo2017extremal}. If we assume that QAOA achieves a constant approximation ratio with $p=1$, then the QAOA cut fraction should also scale as $1/2 + O(1/\sqrt{d})$. This is exactly what we observe, as shown in Figure~\ref{fig:cutfractionbyd}.

Doesn't the figure plotting approximation ratio for p=1 contradict that assumption though?

**Comment by marwahaha** [comment]
Why does it assume a constant approximation ratio? I don't understand that part. 

The one thing that is a little confusing is that the graphs are large, sparse, and random -- but our graphs are small and dense. So I'm not sure if the 1/sqrt(D) behavior should translate.

**Comment by rsln-s** [comment]
But it at least assumes that the QAOA approximation ratio is independent of d? Perhaps I am confused about this. 

So, first, in large sparse random graphs maximal cut value scales as 1/2+O(1/sqrt(d)). Now if QAOA-1 approximation ratio does not depend on d, then you would expect the 1/sqrt(d) scaling. However, if for example the approximation ratio obtained by QAOA-1 goes down with sqrt(d), then scaling of the QAOA-1 cut fraction would be entirely different, e.g 1/d?

**Comment by marwahaha** [comment]
Call me - 9164024661

**Pull request merged**
